# Обычная ориентация клавиатуры - когда кнопки слева, а ручки (knobs) справа.
# Однако можно использовать клавиатуру в другой ориентации.
# Чтобы не запоминать, как меняются кнопки, настройте ориентацию здесь.
# Возможные значения:
#   (горизонтальная ориентация)
#   - 'normal': кнопки слева, ручки справа
#   - 'upsidedown': кнопки справа, ручки слева
#   (вертикальная ориентация)
#   - 'clockwise': кнопки сверху, ручки снизу
#   - 'counterclockwise': кнопки снизу, ручки сверху
orientation: normal

# Количество кнопок и ручек зависит от модели клавиатуры.
# Укажите их здесь для правильной работы.
# Считайте строки и столбцы, держа клавиатуру в нормальной ориентации (кнопки слева, ручки справа).
rows: 2  # Количество строк кнопок
columns: 3  # Количество столбцов кнопок
knobs: 1  # Количество поворотных ручек

# Слои (layers) - это альтернативные схемы раскладки кнопок.
# Переключение между слоями осуществляется с помощью боковой кнопки клавиатуры.
# На момент переключения текущий слой отображается светодиодами.
# Обычно клавиатуры поддерживают три слоя, но возможны и другие варианты.
layers:
  - buttons:
      # Массив кнопок.
      # В горизонтальной ориентации - `rows` строк по `columns` кнопок.
      # В вертикальной ориентации - `columns` строк по `rows` кнопок.
      # Каждая кнопка может быть комбинацией клавиш ('chord') или событием мыши 1234466
      - ["cmd-alt-ctrl-y", "cmd-alt-ctrl-u", "cmd-alt-ctrl-b"] # yandex, chrome, next track
      - [ "cmd-alt-ctrl-h", "cmd-alt-ctrl-i", "cmd-alt-ctrl-o"] # telegram, webstorm, Radix
    knobs:
      # Определение поведения ручек.
      # В горизонтальной ориентации - слева направо.
      # В вертикальной - сверху вниз.
      # Каждая ручка может поворачиваться против часовой стрелки (ccw) или по часовой (cw), а также нажиматься.
      - ccw: "volumedown"  # Уменьшение громкости
        press: "cmd-alt-ctrl-v"  # Нажатие - pause/resume
        cw: "volumeup"  # Увеличение громкости

#  - buttons:
#      # События мыши - клики и прокрутка.
#      # Поддерживаются модификаторы 'ctrl', 'shift' и 'alt'.
#      # Клики могут комбинировать несколько кнопок: 'click+rclick'.
#      - ["click", "lclick"]
#      - ["click+rclick", "wheeldown"]
#      - ["alt-wheelup", "ctrl-click"]
#    knobs:
#      - ccw: "left"  # Поворот влево
#        press: "enter"  # Нажатие - Enter
#        cw: "right"  # Поворот вправо
#
#  - buttons:
#      # Мультимедиа-команды.
#      # Не могут быть смешаны с обычными клавишами и модификаторами.
#      - ["play", "prev"]  # Воспроизведение, предыдущий
#      - ["2", "3"]
#      - ["6", "7"]
#    knobs:
#      - ccw: "wheelup"  # Прокрутка вверх
#        press: "click"  # Обычный клик
#        cw: "wheeldown"  # Прокрутка вниз


# Дополненная информация:
# ### Все возможные клавиши
# - Комбинации клавиш можно соединять через `-`, например `ctrl-alt-del`, `ctrl-shift-7`.
# - Последовательности (до 5 комбинаций) соединяются `,`, например `ctrl-a,ctrl-c`.
# - Можно использовать HID-коды, например `<101>`.
# - События мыши: `click/lclick`, `rclick`, `mclick`, `wheelup`, `wheeldown`.
# - Мультимедийные клавиши: `play`, `prev`, `next`, `mute`, `volumeup`, `volumedown`.
# - Буквы: `a-z`, цифры: `0-9`, `numpad0-numpad9`.
# - Функциональные клавиши: `f1-f24`.
# - Навигация: `insert`, `home`, `pageup`, `delete`, `end`, `pagedown`, `right`, `left`, `down`, `up`.
# - Редактирование: `backspace`, `tab`, `space`, `enter`, `escape`, `capslock`, `printscreen`, `scrolllock`, `pause`.
# - Спецсимволы и пунктуация: `minus`, `equal`, `leftbracket`, `rightbracket`, `backslash`, `semicolon`, `quote`, `comma`, `dot`, `slash`.
# - Системные клавиши: `application`, `power`.
